name: bios8366

channels:
 - conda-forge
 
dependencies:
- python
- arviz
- basemap
- bokeh
- cython
- ipython
- jupyterlab
- notebook
- ipyparallel
- ipykernel
- line_profiler
- mkl-service
- numexpr
- numba
- numpy
- pandas
- patsy
- pip
- pprofile
- proj
- pyarrow
- python-graphviz
- rpy2  
- scikit-learn
- scipy
- seaborn
- snakeviz
- sympy
- pytorch
- catboost
- xlrd
- pip:
  - pymc3
